markdown: redcarpet

pygments: true

redcarpet:
  extensions: ["tables"]

include: ["libraries/master/dojo/_base", "libraries/master/dojo/_firebug"]

excerpt_separator: <!--more-->
paginate: 4
paginate_path: "blog/page:num"

authors:
    cjolif:
        name: Christophe Jolif
        url: https://github.com/cjolif
        gravatar: ca9800fc6cacd919e7dbef9676e2c5f1

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"